import { initializeDatabase, query } from './connection';

async function seedMerchants() {
  await initializeDatabase();

  // Get user IDs
  const users = await query(`SELECT id, role FROM users WHERE is_active = true`);
  const admin      = users.find((u: any) => u.role === 'admin')?.id;
  const commercial = users.find((u: any) => u.role === 'commercial')?.id;
  const onboarding = users.find((u: any) => u.role === 'onboarding')?.id;

  if (!admin) {
    console.error('❌ No users found. Run seed.ts first.');
    process.exit(1);
  }

  const assignees = [admin, commercial, onboarding].filter(Boolean);
  const pick = (arr: any[]) => arr[Math.floor(Math.random() * arr.length)];

  const merchants = [
    {
      legal_name: 'Supermercados La Canasta S.A.C.',
      trade_name: 'La Canasta',
      tax_id: '20501234567',
      country: 'Perú',
      city: 'Lima',
      state: 'Lima',
      address: 'Av. Javier Prado Este 4200, San Borja',
      postal_code: '15036',
      website: 'https://lacanasta.com.pe',
      mcc_code: '5411',
      mcc_description: 'Grocery Stores, Supermarkets',
      business_type: 'Retail',
      industry: 'Alimentación',
      contact_name: 'Carlos Mendoza Ríos',
      contact_email: 'cmendoza@lacanasta.com.pe',
      contact_phone: '+51 1 234-5678',
      contact_position: 'Gerente Financiero',
      bank_name: 'BCP',
      bank_account_number: '194-12345678-0-12',
      bank_account_type: 'checking',
      bank_swift: 'BCPLPEPL',
      currency: 'PEN',
      monthly_volume: 850000,
      average_ticket: 120,
      max_transaction: 5000,
      min_transaction: 5,
      accepts_credit_card: true,
      accepts_debit_card: true,
      accepts_ach: false,
      accepts_wire: true,
      accepts_crypto: false,
      integration_type: 'api',
      api_endpoint: 'https://api.lacanasta.com.pe/payments',
      webhook_url: 'https://api.lacanasta.com.pe/webhooks/prontopaga',
      status: 'certified',
      risk_level: 'low',
      tags: ['vip', 'retail', 'certificado'],
      notes: 'Cliente premium. Integración completada sin incidencias.',
    },
    {
      legal_name: 'TechSolutions Chile SpA',
      trade_name: 'TechSol',
      tax_id: '76.543.210-K',
      country: 'Chile',
      city: 'Santiago',
      state: 'Región Metropolitana',
      address: 'Av. Apoquindo 4501, Las Condes',
      postal_code: '7550000',
      website: 'https://techsol.cl',
      mcc_code: '7372',
      mcc_description: 'Computer Programming, Data Processing',
      business_type: 'SaaS',
      industry: 'Tecnología',
      contact_name: 'Valentina Torres',
      contact_email: 'vtorres@techsol.cl',
      contact_phone: '+56 2 2345-6789',
      contact_position: 'CEO',
      bank_name: 'Banco de Chile',
      bank_account_number: '00-123-45678-09',
      bank_account_type: 'checking',
      bank_swift: 'BCHICLRM',
      currency: 'CLP',
      monthly_volume: 45000000,
      average_ticket: 150000,
      max_transaction: 2000000,
      min_transaction: 10000,
      accepts_credit_card: true,
      accepts_debit_card: true,
      accepts_ach: true,
      accepts_wire: true,
      accepts_crypto: false,
      integration_type: 'sdk',
      api_endpoint: 'https://payments.techsol.cl/v2',
      webhook_url: 'https://payments.techsol.cl/hooks',
      status: 'approved',
      risk_level: 'low',
      tags: ['tech', 'saas', 'chile'],
      notes: 'Empresa de software con alto volumen. Aprobada, pendiente certificación.',
    },
    {
      legal_name: 'Restaurantes El Sabor Ecuatoriano Cía. Ltda.',
      trade_name: 'El Sabor',
      tax_id: '1791234567001',
      country: 'Ecuador',
      city: 'Guayaquil',
      state: 'Guayas',
      address: 'Av. Francisco de Orellana, Edificio World Trade Center',
      postal_code: '090150',
      website: 'https://elsabor.ec',
      mcc_code: '5812',
      mcc_description: 'Eating Places, Restaurants',
      business_type: 'Restaurante',
      industry: 'Gastronomía',
      contact_name: 'Roberto Alvarado',
      contact_email: 'ralvarado@elsabor.ec',
      contact_phone: '+593 4 234-5678',
      contact_position: 'Director Operativo',
      bank_name: 'Banco Pichincha',
      bank_account_number: '2200123456',
      bank_account_type: 'savings',
      currency: 'USD',
      monthly_volume: 95000,
      average_ticket: 35,
      max_transaction: 500,
      min_transaction: 5,
      accepts_credit_card: true,
      accepts_debit_card: true,
      accepts_ach: false,
      accepts_wire: false,
      accepts_crypto: false,
      integration_type: 'hosted',
      status: 'in_review',
      risk_level: 'medium',
      tags: ['gastronomia', 'ecuador'],
      notes: 'En proceso de revisión de documentación bancaria.',
    },
    {
      legal_name: 'Farmacia Salud Total S.A.',
      trade_name: 'Salud Total',
      tax_id: '20612345678',
      country: 'Perú',
      city: 'Arequipa',
      state: 'Arequipa',
      address: 'Calle Mercaderes 234, Centro Histórico',
      postal_code: '04001',
      website: 'https://saludtotal.pe',
      mcc_code: '5912',
      mcc_description: 'Drug Stores and Pharmacies',
      business_type: 'Farmacia',
      industry: 'Salud',
      contact_name: 'María Elena Quispe',
      contact_email: 'mquispe@saludtotal.pe',
      contact_phone: '+51 54 234-567',
      contact_position: 'Administradora',
      bank_name: 'Interbank',
      bank_account_number: '200-3012345678',
      bank_account_type: 'checking',
      currency: 'PEN',
      monthly_volume: 320000,
      average_ticket: 85,
      max_transaction: 2000,
      min_transaction: 10,
      accepts_credit_card: true,
      accepts_debit_card: true,
      accepts_ach: false,
      accepts_wire: false,
      accepts_crypto: false,
      integration_type: 'plugin',
      status: 'documentation_required',
      risk_level: 'medium',
      tags: ['salud', 'farmacia', 'arequipa'],
      notes: 'Falta enviar copia de licencia sanitaria y RUC actualizado.',
    },
    {
      legal_name: 'Importadora Andina Chile S.A.',
      trade_name: 'Andina Import',
      tax_id: '77.891.234-5',
      country: 'Chile',
      city: 'Valparaíso',
      state: 'Valparaíso',
      address: 'Puerto de Valparaíso, Bodega 12',
      postal_code: '2340000',
      website: 'https://andinaimport.cl',
      mcc_code: '5065',
      mcc_description: 'Electrical Parts and Equipment',
      business_type: 'Importadora',
      industry: 'Comercio Exterior',
      contact_name: 'Andrés Fuentes',
      contact_email: 'afuentes@andinaimport.cl',
      contact_phone: '+56 32 234-5678',
      contact_position: 'Gerente Comercial',
      bank_name: 'Santander Chile',
      bank_account_number: '0-000-1234567-0',
      bank_account_type: 'checking',
      bank_swift: 'BSCHCLRM',
      bank_iban: 'CL12345678901234567890',
      currency: 'USD',
      monthly_volume: 1200000,
      average_ticket: 8500,
      max_transaction: 150000,
      min_transaction: 500,
      accepts_credit_card: false,
      accepts_debit_card: false,
      accepts_ach: true,
      accepts_wire: true,
      accepts_crypto: false,
      integration_type: 'api',
      api_endpoint: 'https://erp.andinaimport.cl/api/payments',
      status: 'pending',
      risk_level: 'high',
      tags: ['importadora', 'b2b', 'alto-volumen'],
      notes: 'Empresa con operaciones internacionales. Requiere revisión de compliance.',
    },
    {
      legal_name: 'Tienda Online Moda EC S.A.S.',
      trade_name: 'ModaEC',
      tax_id: '1792345678001',
      country: 'Ecuador',
      city: 'Quito',
      state: 'Pichincha',
      address: 'Av. Naciones Unidas E7-26, Quito',
      postal_code: '170515',
      website: 'https://modaec.com',
      mcc_code: '5651',
      mcc_description: 'Family Clothing Stores',
      business_type: 'E-commerce',
      industry: 'Moda',
      contact_name: 'Gabriela Moreno',
      contact_email: 'gmoreno@modaec.com',
      contact_phone: '+593 2 345-6789',
      contact_position: 'Fundadora',
      bank_name: 'Produbanco',
      bank_account_number: '12001234567',
      bank_account_type: 'savings',
      currency: 'USD',
      monthly_volume: 28000,
      average_ticket: 65,
      max_transaction: 800,
      min_transaction: 15,
      accepts_credit_card: true,
      accepts_debit_card: true,
      accepts_ach: false,
      accepts_wire: false,
      accepts_crypto: true,
      integration_type: 'api',
      api_endpoint: 'https://modaec.com/api/checkout',
      webhook_url: 'https://modaec.com/webhooks',
      status: 'lead',
      risk_level: 'low',
      tags: ['ecommerce', 'moda', 'startup'],
      notes: 'Startup en crecimiento. Primer contacto realizado por LinkedIn.',
    },
    {
      legal_name: 'Constructora Pacífico S.A.C.',
      trade_name: 'Pacífico Construye',
      tax_id: '20723456789',
      country: 'Perú',
      city: 'Trujillo',
      state: 'La Libertad',
      address: 'Av. España 1234, Trujillo',
      postal_code: '13001',
      website: 'https://pacificoconstruye.pe',
      mcc_code: '5999',
      mcc_description: 'Miscellaneous and Specialty Retail Stores',
      business_type: 'Construcción',
      industry: 'Inmobiliaria',
      contact_name: 'Jorge Castillo',
      contact_email: 'jcastillo@pacificoconstruye.pe',
      contact_phone: '+51 44 234-5678',
      contact_position: 'Gerente General',
      bank_name: 'BBVA Perú',
      bank_account_number: '0011-0123-01-00123456',
      bank_account_type: 'checking',
      bank_swift: 'BCONPEPL',
      currency: 'PEN',
      monthly_volume: 2500000,
      average_ticket: 45000,
      max_transaction: 500000,
      min_transaction: 1000,
      accepts_credit_card: false,
      accepts_debit_card: false,
      accepts_ach: true,
      accepts_wire: true,
      accepts_crypto: false,
      integration_type: 'manual',
      status: 'suspended',
      risk_level: 'critical',
      tags: ['construccion', 'b2b', 'suspendido'],
      notes: 'Suspendido por inconsistencias en documentación fiscal. En revisión legal.',
    },
    {
      legal_name: 'Hotel Boutique Viña del Mar S.A.',
      trade_name: 'Hotel Pacífico Viña',
      tax_id: '78.234.567-8',
      country: 'Chile',
      city: 'Viña del Mar',
      state: 'Valparaíso',
      address: 'Av. San Martín 667, Viña del Mar',
      postal_code: '2520000',
      website: 'https://hotelpacificovina.cl',
      mcc_code: '7011',
      mcc_description: 'Hotels, Motels, Resorts',
      business_type: 'Hotelería',
      industry: 'Turismo',
      contact_name: 'Sofía Reyes',
      contact_email: 'sreyes@hotelpacificovina.cl',
      contact_phone: '+56 32 345-6789',
      contact_position: 'Directora General',
      bank_name: 'BCI',
      bank_account_number: '12345678',
      bank_account_type: 'checking',
      bank_swift: 'CREDCLRM',
      currency: 'CLP',
      monthly_volume: 85000000,
      average_ticket: 180000,
      max_transaction: 3000000,
      min_transaction: 50000,
      accepts_credit_card: true,
      accepts_debit_card: true,
      accepts_ach: false,
      accepts_wire: true,
      accepts_crypto: false,
      integration_type: 'hosted',
      webhook_url: 'https://hotelpacificovina.cl/prontopaga/hook',
      status: 'approved',
      risk_level: 'low',
      tags: ['turismo', 'hotel', 'chile'],
      notes: 'Hotel 4 estrellas. Integración con PMS Cloudbeds en progreso.',
    },
    {
      legal_name: 'Clínica Dental Sonrisa Perfecta S.R.L.',
      trade_name: 'Sonrisa Perfecta',
      tax_id: '1790987654001',
      country: 'Ecuador',
      city: 'Cuenca',
      state: 'Azuay',
      address: 'Av. Remigio Crespo 5-89, Cuenca',
      postal_code: '010101',
      website: 'https://sonrisaperfecta.ec',
      mcc_code: '8049',
      mcc_description: 'Offices and Clinics of Other Health Practitioners',
      business_type: 'Clínica',
      industry: 'Salud',
      contact_name: 'Dr. Pablo Vega',
      contact_email: 'pvega@sonrisaperfecta.ec',
      contact_phone: '+593 7 234-5678',
      contact_position: 'Director Médico',
      bank_name: 'Banco del Austro',
      bank_account_number: '3001234567',
      bank_account_type: 'savings',
      currency: 'USD',
      monthly_volume: 18000,
      average_ticket: 250,
      max_transaction: 3000,
      min_transaction: 20,
      accepts_credit_card: true,
      accepts_debit_card: true,
      accepts_ach: false,
      accepts_wire: false,
      accepts_crypto: false,
      integration_type: 'plugin',
      status: 'rejected',
      risk_level: 'medium',
      tags: ['salud', 'clinica', 'ecuador'],
      notes: 'Rechazado por no cumplir requisitos mínimos de volumen mensual. Puede repostular en 90 días.',
    },
    {
      legal_name: 'Distribuidora Norte S.A.C.',
      trade_name: 'DistriNorte',
      tax_id: '20834567890',
      country: 'Perú',
      city: 'Chiclayo',
      state: 'Lambayeque',
      address: 'Av. Balta 1234, Chiclayo',
      postal_code: '14001',
      website: 'https://distrinorte.pe',
      mcc_code: '5045',
      mcc_description: 'Computers, Peripherals, and Software',
      business_type: 'Distribuidora',
      industry: 'Tecnología',
      contact_name: 'Luis Sánchez',
      contact_email: 'lsanchez@distrinorte.pe',
      contact_phone: '+51 74 234-5678',
      contact_position: 'Jefe de Ventas',
      secondary_contact_name: 'Ana Flores',
      secondary_contact_email: 'aflores@distrinorte.pe',
      secondary_contact_phone: '+51 74 234-5679',
      bank_name: 'Scotiabank Perú',
      bank_account_number: '000-1234567',
      bank_account_type: 'checking',
      currency: 'PEN',
      monthly_volume: 420000,
      average_ticket: 1200,
      max_transaction: 25000,
      min_transaction: 100,
      accepts_credit_card: true,
      accepts_debit_card: true,
      accepts_ach: true,
      accepts_wire: false,
      accepts_crypto: false,
      integration_type: 'api',
      api_endpoint: 'https://distrinorte.pe/api/v1/payments',
      webhook_url: 'https://distrinorte.pe/webhooks',
      ip_whitelist: ['190.235.12.45', '190.235.12.46'],
      technical_contact_email: 'tech@distrinorte.pe',
      technical_contact_phone: '+51 74 234-5680',
      status: 'in_review',
      risk_level: 'medium',
      tags: ['distribucion', 'tech', 'norte'],
      notes: 'Segunda empresa del grupo. Revisión en curso.',
    },
  ];

  console.log('🌱 Insertando 10 comercios de demo...\n');

  for (const m of merchants) {
    // Get assigned user
    const assignedTo = pick(assignees);

    const result = await query(
      `INSERT INTO merchants (
        legal_name, trade_name, tax_id, country, city, state, address, postal_code, website,
        mcc_code, mcc_description, business_type, industry,
        contact_name, contact_email, contact_phone, contact_position,
        secondary_contact_name, secondary_contact_email, secondary_contact_phone,
        bank_name, bank_account_number, bank_account_type, bank_swift, bank_iban, currency,
        monthly_volume, average_ticket, max_transaction, min_transaction,
        accepts_credit_card, accepts_debit_card, accepts_ach, accepts_wire, accepts_crypto,
        payment_methods_detail,
        integration_type, api_endpoint, webhook_url, ip_whitelist,
        technical_contact_email, technical_contact_phone,
        status, risk_level, assigned_to, notes, tags, created_by,
        last_activity_at
      ) VALUES (
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
        $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,
        $39,$40,$41,$42,$43,$44,$45,$46,$47,$48,
        NOW() - (random() * interval '30 days')
      ) RETURNING id, legal_name, status`,
      [
        m.legal_name, m.trade_name || null, m.tax_id, m.country, m.city || null,
        m.state || null, m.address || null, m.postal_code || null, m.website || null,
        m.mcc_code, m.mcc_description || null, m.business_type || null, m.industry || null,
        m.contact_name, m.contact_email, m.contact_phone || null, m.contact_position || null,
        (m as any).secondary_contact_name || null, (m as any).secondary_contact_email || null,
        (m as any).secondary_contact_phone || null,
        m.bank_name || null, m.bank_account_number || null, m.bank_account_type || null,
        (m as any).bank_swift || null, (m as any).bank_iban || null,
        m.currency || 'USD',
        m.monthly_volume || null, m.average_ticket || null,
        m.max_transaction || null, m.min_transaction || null,
        m.accepts_credit_card, m.accepts_debit_card, m.accepts_ach, m.accepts_wire, m.accepts_crypto,
        '[]',
        m.integration_type || null, (m as any).api_endpoint || null,
        (m as any).webhook_url || null,
        (m as any).ip_whitelist || [],
        (m as any).technical_contact_email || null, (m as any).technical_contact_phone || null,
        m.status, m.risk_level, assignedTo, m.notes || null,
        m.tags || [],
        assignedTo,
      ]
    );

    const merchant = result[0];
    console.log(`  ✅ ${merchant.legal_name} → [${merchant.status.toUpperCase()}]`);

    // Add status history for non-lead merchants
    if (m.status !== 'lead') {
      await query(
        `INSERT INTO merchant_status_history (merchant_id, changed_by, old_status, new_status, reason)
         VALUES ($1, $2, $3, $4, $5)`,
        [merchant.id, assignedTo, 'lead', m.status, 'Actualización inicial de estado']
      );
    }

    // Add a comment
    const comments = [
      'Primer contacto realizado. Cliente interesado en integración API.',
      'Documentación recibida y en revisión por el equipo de compliance.',
      'Llamada de seguimiento programada para la próxima semana.',
      'Se solicitaron documentos adicionales al contacto principal.',
      'Integración técnica completada exitosamente.',
      'Cliente confirmó volumen mensual estimado.',
      'Revisión de contrato en proceso con el área legal.',
    ];
    await query(
      `INSERT INTO comments (merchant_id, user_id, content, is_internal)
       VALUES ($1, $2, $3, true)`,
      [merchant.id, assignedTo, pick(comments)]
    );

    // Add a task
    const tasks = [
      'Verificar documentos de identidad del representante legal',
      'Completar integración técnica con el equipo de desarrollo',
      'Enviar contrato para firma digital',
      'Validar cuenta bancaria con prueba de micro-depósito',
      'Programar llamada de onboarding con el cliente',
      'Revisar historial crediticio del comercio',
    ];
    const priorities = ['medium', 'high', 'urgent', 'low'];
    await query(
      `INSERT INTO tasks (merchant_id, created_by, assigned_to, title, priority, status)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [
        merchant.id, assignedTo, assignedTo,
        pick(tasks), pick(priorities),
        m.status === 'certified' ? 'completed' : 'pending',
      ]
    );
  }

  // Recalculate scores for all inserted merchants
  const allMerchants = await query(`SELECT id FROM merchants`);
  console.log(`\n📊 Calculando scores para ${allMerchants.length} comercios...`);

  for (const m of allMerchants) {
    // Simple score update based on completeness
    await query(
      `UPDATE merchants SET score = FLOOR(30 + random() * 60) WHERE id = $1`,
      [m.id]
    );
  }

  console.log('\n✅ 10 comercios insertados con éxito');
  console.log('📋 Estados: certified, approved (x2), in_review (x2), pending, documentation_required, suspended, rejected, lead');
  process.exit(0);
}

seedMerchants().catch(err => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});
